#ifndef DEFINES_H
#define DEFINES_H

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720

#define MAP_OFFSET_HEIGHT WINDOW_HEIGHT / 2
#define MAP_OFFSET_WIDTH WINDOW_WIDTH / 2

#define TILE_WIDTH 10
#define TILE_HEIGHT 10

#define DT_THRESHOLD_DEFAULT 4 * 10000000

#define PLAYER_VELOCITY 120

#define SHOW_2D 0
#define SHOW_TEXTURES 1

#endif